- docs/design/.pages
- docs/design/autoware-concepts/.pages
- docs/design/autoware-concepts/index.md
- docs/design/index.md
Before talking about Autoware's interfaces or other things, we need to show the concept of Autoware.
> docs: add an empty page of Autoware concepts

- docs/contributing/.pages
- docs/contributing/index.md
- docs/contributing/license.md
Moved from https://github.com/autowarefoundation/autoware/pull/29.
> docs: add the license page

- .github/workflows/deploy-docs.yaml
Related https://github.com/autowarefoundation/autoware-github-actions/issues/96
Added a condition for `latest` to correct a malfunction in `pull_request_target`.
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
> fix(deploy-docs): fix latest condition

- docs/help/support-guidelines.md
I've also used https://shields.io/ for the interactive join link.
> docs(support-guidelines): replace slack with discord references

- docs/installation/autoware/docker-installation.md
This PR adds manual installation steps for the Autoware Docker Installation.
> docs(docker-installation): add manual installation steps

- docs/tutorials/ad-hoc-simulation/planning-simulation.md
add `source ~/autoware/install/setup.bash` before `ros2 topic pub /autoware/engage autoware_auto_vehicle_msgs/msg/Engage "engage: true" -1` in the tutorial page of planning_simulation.
Without souring setup.bash, `ros2 topic pub...` will fail with the error message `The passed message type is invalid`.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/ …
> docs: fix planning-simulation.md

- docs/installation/autoware/docker-installation.md
The command in docker installation tutorial is only for NVIDIA GPU.
If running container without GPU, it'll fail.
Thanks to @kenji-miyake for providing solution [here](https://github.com/autowarefoundation/autoware-documentation/pull/73#issuecomment-1090136882).
> docs: add how to run docker without NVIDIA GPU.

- docs/contributing/index.md
Signed-off-by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>
Fixing broken anchor in the table of contents for the "How can I get help?" section. GitHub's markdown ignores capitals in anchor links but it seems that MkDocs is more strict.
> docs: fix broken anchor

- docs/contributing/index.md
Signed-off-by: IshitaTakeshi <ishitah.takeshi@gmail.com>
I thought that contributors might be curious that their proposals deserve to open Q&A and pull requests, so I added more concrete example cases
https://github.com/autowarefoundation/autoware/discussions/271
> docs: add more concrete example cases of making PRs

- mkdocs.yaml
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
mdx_unimoji is deprecated and it should be deleted since https://github.com/autowarefoundation/autoware-github-actions/issues/145
Related PR
https://github.com/autowarefoundation/autoware-github-actions/pull/146
The PR reviewers **must** check the checkboxes below before approval.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines …
> ci(deploy-docs): remove mdx_unimoji

- mkdocs.yaml
It might be good that the GitHub link on the top right of the documentation is linked to https://github.com/autowarefoundation/autoware instead of autoware-documentation.
Then, we can guide people to the main repository.
What do you think about it?
> docs: change repo_url to autoware meta repository

- docs/how-to-guides/how-to-integrate-autoware-with-your-vehicle.md
Signed-off-by: Shark Liu <huiyuan.liu@autocore.ai>
Fix dead link in "How to integrate Autoware with your vehicle" page
> docs: fix dead link in how-to-guides

- docs/contributing/coding-guidelines/ros-nodes/message-guidelines.md
- docs/contributing/index.md
- docs/contributing/pull-request-guidelines/commit-guidelines.md
- docs/contributing/pull-request-guidelines/index.md
- docs/contributing/pull-request-guidelines/review-tips.md
- docs/design/autoware-concepts/index.md
- docs/design/autoware-interfaces/components/planning.md
- docs/how-to-guides/advanced-usage-of-colcon.md
- docs/how-to-guides/how-to-integrate-autoware-with-your-vehicle.md
- docs/installation/additional-settings-for-developers/index.md
- docs/installation/autoware/docker-installation.md
- docs/installation/autoware/source-installation.md
- docs/installation/index.md
- docs/support/support-guidelines.md
Resolves #51.
Fixed some styles in accordance with the following guidelines:
- https://developers.google.com/style/person?hl=en
- https://developers.google.com/style/clause-order
> docs: fix styles

- docs/contributing/coding-guidelines/.pages
- docs/contributing/coding-guidelines/index.md
- docs/contributing/coding-guidelines/languages/.pages
- docs/contributing/coding-guidelines/languages/cmake.md
- docs/contributing/coding-guidelines/languages/cpp.md
- docs/contributing/coding-guidelines/languages/docker.md
- docs/contributing/coding-guidelines/languages/github-actions.md
- docs/contributing/coding-guidelines/languages/index.md
- docs/contributing/coding-guidelines/languages/markdown.md
- docs/contributing/coding-guidelines/languages/package-xml.md
- docs/contributing/coding-guidelines/languages/python.md
- docs/contributing/coding-guidelines/languages/ros2-interfaces.md
- docs/contributing/coding-guidelines/languages/shell-scripts.md
- docs/contributing/coding-guidelines/ros-nodes/.pages
- docs/contributing/coding-guidelines/ros-nodes/index.md
- docs/contributing/discussion-guidelines/index.md
- docs/contributing/documentation-guidelines/index.md
- docs/contributing/pull-request-guidelines/review-guidelines.md
Added minimal coding guidelines that only have links.
I'll add more information as soon as possible, but I'd like to merge this for now.
> docs: add minimal coding guidelines

- docs/contributing/testing-guidelines/integration-testing.md
- docs/contributing/testing-guidelines/unit-testing.md
Signed-off-by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>
Minor fixes for the newly added integration and unit testing guidelines
> docs(guidelines): update integration unit testing guidelines

- .gitignore
- includes/abbreviations.md
- mkdocs.yaml
Signed-off-by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>
In the Autoware documentation, acronyms are used quite often (eg: AWF for Autoware Foundation) but when doing so we always have to consider adding an explanation for an acronym the first time it is used on a particular page. However, this process can lead to duplicate explanations across multiple pages of the documentation. One potential solution to this problem is to create a glossary that can be used as a single source of explanation for acronyms and commonly used terms that may be unknown to new Autoware contributors.
I created a [discussion to get feedback on potential solutions](https://github.com/autowarefoundation/autoware/discussions/389#discussion-4112318), and the initial suggestion was to start with a basic …
> feat: add glossary

- docs/installation/autoware/docker-installation.md
Following discussions in [this issue](https://github.com/autowarefoundation/autoware/issues/2821), I found that not all dependencies were installed in the docker image.
This PR adds commands to install missing dependencies to the Docker installation instructions.
> docs(docker): add cmd for missing dependencies

- docs/support/support-guidelines.md
Signed-off-by: Shigekazu Fukuta <shigekazu.fukuta@tier4.jp>
Add link how to create github discussion in support guideline.
> feat(support-guidelines): add link to GitHub Docs

- docs/tutorials/scenario-simulation/planning-simulation/installation.md
- docs/tutorials/scenario-simulation/planning-simulation/random-test-simulation.md
Add -y to `rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO`,
which is in the installation of Scenario simulation tutorial.
This can avoid too many annoying installation checkings.
Also fix the markdown link in [the tutorial](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/scenario-simulation/planning-simulation/random-test-simulation/#running-steps). …
> fix(tutorial): add -y for rosdep and fix markdown link

- docs/installation/autoware/docker-installation.md
The `latest` image doesn't contain `CUDA` after https://github.com/autowarefoundation/autoware_core_universe_prototype/pull/346, which may cause some errors in the tutorial.
Related: https://github.com/autowarefoundation/autoware/issues/2821
Please refer to https://github.com/autowarefoundation/autoware/pkgs/container/autoware-universe/versions for all tags. …
> fix(docker-installation): use -cuda images

- docs/installation/autoware/docker-installation.md
- docs/tutorials/ad-hoc-simulation/planning-simulation.md
- docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
While trying [examples](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/ad-hoc-simulation/planning-simulation/) in docker containers, it's inconvenience to download files directly from Google Drive. Besides, there is no `Downloads` folder in docker container, so users should modify the path by themselves. Suggest to use `wget` instead.
Refer to [here](https://www.matthuisman.nz/2019/01/download-google-drive-files-wget-curl.html) for how to download files from Google Drive with wget. …
> fix(tutorials): use gdown to download files from Google Drive

- docs/design/autoware-interfaces/index.md
The package has been moved and renamed.
> fix(design/autoware-interfaces): fix the link of ResponseStatus

- docs/design/autoware-interfaces/components/control.md
- docs/installation/autoware/docker-installation.md
- docs/installation/autoware/source-installation.md
- docs/support/troubleshooting.md
The PR includes the following:
1. Add "how to limit build job" while there are too many CPU cores.
- This is the problem I met [here](https://github.com/autowarefoundation/autoware/discussions/2901)
2. Add troubleshooting link in installation pages.
- Troubleshooting page is a little hard to find. While build error, I don't know there is "build issue" section in troubleshooting page.
3. Fix markdown link. …
> docs(installation): add troubleshooting link to installation

- mkdocs.yaml
As described [here](https://github.com/autowarefoundation/open-ad-kit-docs/pull/34#issuecomment-1264212294), add markdown_extensions to support emoji in mkdocs.
> chore: support emoji for mkdocs.

- docs/design/autoware-architecture/planning/index.md
Signed-off-by: kosuke55 <kosuke.tnp@gmail.com>
Some modules and functions do not support paths with only one point, so add it to the limitations of docs.
> docs(planning): add limitation of path points size

- docs/design/autoware-interfaces/ad-api/list/api/planning/index.md
- docs/design/autoware-interfaces/ad-api/list/api/planning/steering_factors.md
- docs/design/autoware-interfaces/ad-api/list/api/planning/velocity_factors.md
- docs/design/autoware-interfaces/index.md
Reflect the results of discussions of AD API PRs.
> feat: reflect the review discussions

- docs/installation/autoware/source-installation.md
Signed-off-by: mitsudome-r <ryohsuke.mitsudome@tier4.jp>
As we are switching to ROS 2 Humble in the main branch of Autoware, we should modify the instruction to use specify galactic branch if people wish to use galactic.
https://github.com/autowarefoundation/autoware/issues/3083 …
> fix(docs): fix source installation instruction to use galactic branch

- docs/contributing/coding-guidelines/ros-nodes/message-guidelines.md
- docs/installation/autoware/docker-installation.md
- docs/installation/autoware/source-installation.md
- docs/tutorials/scenario-simulation/planning-simulation/installation.md
Signed-off-by: mitsudome-r <ryohsuke.mitsudome@tier4.jp>
We are transitioning to ROS 2 Humble, and we no longer guarantee building on Galactic.
This PR would remove galactic related instruction.
Related Issue/Discussions/PRs:
https://github.com/orgs/autowarefoundation/discussions/2622
https://github.com/autowarefoundation/autoware/issues/3083 …
> fix(docs): update documentation for humble from galactic

- docs/design/autoware-interfaces/ad-api/list/api/localization/index.md
- docs/design/autoware-interfaces/ad-api/list/api/motion/index.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/index.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/index.md
Signed-off-by: h-ohta <hiroki.ota@tier4.jp>
- fix titles in ADAPI
- fix state WAITING -> UNSET on Routing
> fix: titles in ADAPI and state on Routing

- .markdown-link-check.json
- docs/contributing/coding-guidelines/languages/cpp.md
Fixes failing pre-commit-optional ci: https://github.com/autowarefoundation/autoware-documentation/actions/runs/3767529962/jobs/6405151006
> fix(dead-link): update dead autosar link

- docs/contributing/coding-guidelines/ros-nodes/message-guidelines.md
Add plural type naming to message guidelines. See https://github.com/autowarefoundation/autoware-documentation/issues/296 for details.
> docs(message-guidelines): add plural type naming

- docs/design/autoware-architecture/sensing/data-types/gnss-ins-data.md
- docs/design/autoware-architecture/sensing/data-types/image.md
- docs/design/autoware-architecture/sensing/data-types/point-cloud.md
- docs/design/autoware-architecture/sensing/data-types/radar-data.md
- docs/design/autoware-architecture/sensing/data-types/ultrasonics-data.md
- docs/design/autoware-architecture/sensing/index.md
This PR adds documentation for sensing part of the autoware modules.
I've separated the design docs by data types.
- Sensing/Perception Architecture Design
- https://github.com/orgs/autowarefoundation/discussions/2456
- Point Types
- https://github.com/orgs/autowarefoundation/discussions/2480 …
> docs(sensing): add sensing design documentation

- docs/support/troubleshooting.md
Signed-off-by: Lukasz Chojnacki <lukasz.chojnacki@robotec.ai>
Related to the issue https://github.com/autowarefoundation/autoware.universe/issues/2755
> docs(support/troubleshooting): add information about setuptools issue in the troubleshooting section

- mkdocs.yaml
The footer navigation is gone.
The major version of mkdocs material has been upgraded and a new configuration item has been added.
https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation
This PR will enable the above settings and behave the same as before
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guideli …
> build(mkdocs.yaml): add navigation.footer

- docs/contributing/pull-request-guidelines/index.md
Add the definition of standard change and small change for PR template.
The motivation is to ensure that the PR authors do not confuse which template to use. 
e.g. even minor feature or bug fix PR should be written in standard template
> feat(contributing): add the definition of standard change and small change for PR

- docs/support/troubleshooting.md
Related to the issue https://github.com/autowarefoundation/autoware.universe/issues/2755
Updated information about setuptools in the troubleshooting section.
> docs(support/troubleshooting): update information about python setuptools in troubleshooting section

- docs/how-to-guides/creating-maps-for-autoware.md
I've updated the broken MapIV Engine link since the MapIV website has been renewed.
Sorry,  I forgot to correct in the following PR.
https://github.com/autowarefoundation/autoware-documentation/pull/349
> fix: fix the broken link for MapIV Engine

- docs/support/troubleshooting.md
Add how to reduce memory usage while buildng.
I referred to documents below.
- https://answers.ros.org/question/368249/colcon-build-number-of-threads/
- https://colcon.readthedocs.io/en/released/reference/executor-arguments.html
- [Tech blog about autoware](https://medium.com/tier-iv-tech-blog/autoware%E3%81%AE%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB%E3%81%A8component%E3%81%AE%E3%83%8F%E3%82%A4%E3%83%AC%E3%83%99%E3%83%AB%E3%81%AA%E8%A8%AD%E8%A8%88-67a8a2a1b9ba#:~:text=MAKEFLAGS%3D%2Dj1%20colcon%20build%20%2D%2Dcmake%2Dargs%20%2DDCMAKE_BUILD_TYPE%3DRelease%20%2D%2Dparallel%2Dworkers%201%20%23%20MAKEFLAGS%E3%81%AF%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E5%86%85%E3%81%AE%E4%B8%A6%E5%88%97%E6%95%B0%E3%80%81parallel%2Dworkers%E3%81%AF%E3%83%91%E3%83%83%E3%82%B1%E3%8 …
> feat: add how to reduce memory usage while building

- docs/tutorials/scenario-simulation/.pages
- docs/tutorials/scenario-simulation/index.md
Add scenario simulation page because 
Adhoc sim has a page provided, but scenerio sim does not have a page provided and is not in bold black type.
It is difficult for users to see that there are two, Adhoc and Scenario, which can be confusing.
> docs: add scenario simulation page

- docs/assets/js/mathjax.js
- mkdocs.yaml
Equations [in this page](https://autowarefoundation.github.io/autoware-documentation/main/how-to-guides/integrating-autoware/creating-vehicle-interface-package/customizing-for-differential-drive-model/) were not rendered, so I fixed it.
> build(mkdocs): fix mathjax rendering

- docs/design/autoware-interfaces/ad-api/list/api/routing/index.md
Add goal modification option to routing API. See https://github.com/autowarefoundation/autoware/issues/3406 for details.
> feat: add description of goal modification

- docs/design/autoware-interfaces/components/planning.md
This PR updates the Planning Interface information to the latest Autoware. 
> docs(planning-interface): update to the latest interface information

- .github/sync-files.yaml
- mkdocs-base.yaml
The `mkdocs.yaml` in this repository had two roles. One is the config file and another is the template for sync files workflow. When I added this repository-specific setting, it affected the sync destination as well. So I separated the files for each role.
- `mkdocs.yaml`: the config file with repository-specific setting
- `mkdocs-base-yaml`: the template file for sync files workflow.
Ideally, template files are placed in a dedicated repository.
[contribution guidelines]: …
> chore: add mkdocs template for sync files from other repository

- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-description/creating-vehicle-and-sensor-description.md
PR for #396, which add document for `Creating vehicle and sensor description`.
> docs(how-to-guides): add creating vehicle and sensor description.

- docs/design/autoware-interfaces/ad-api/list/api/fail_safe/mrm_state.md
- docs/design/autoware-interfaces/ad-api/list/api/interface/version.md
- docs/design/autoware-interfaces/ad-api/list/api/localization/initialization_state.md
- docs/design/autoware-interfaces/ad-api/list/api/localization/initialize.md
- docs/design/autoware-interfaces/ad-api/list/api/motion/accept_start.md
- docs/design/autoware-interfaces/ad-api/list/api/motion/state.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_autonomous.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_local.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_remote.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/change_to_stop.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/disable_autoware_control.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/enable_autoware_control.md
- docs/design/autoware-interfaces/ad-api/list/api/operation_mode/state.md
- docs/design/autoware-interfaces/ad-api/list/api/planning/steering_factors.md
- docs/design/autoware-interfaces/ad-api/list/api/planning/velocity_factors.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/clear_route.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/route.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/set_route.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/set_route_points.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/state.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/dimensions.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/doors/layout.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/doors/status.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/kinematics.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/status.md
- docs/design/autoware-interfaces/templates/autoware-interface.jinja2
- tools/autoware-interfaces/generate.py
Add "Latest Version" for release status to each page of AD API.
> feat(ad-api): add release status

- docs/how-to-guides/index.md
- docs/how-to-guides/others/an-example-procedure-for-adding-a-new-node.md
- docs/how-to-guides/others/an-example-procedure-for-adding-and-evaluating-a-new-node.md
PR for https://github.com/autowarefoundation/autoware-documentation/issues/400, which add document about procedure of introducing a new node of localization.
The added pages leads to the necessary information rather than adding new information.
> docs(how-to-guides): add example procedure, case of localization

- docs/design/autoware-architecture/map/index.md
Related to https://github.com/autowarefoundation/autoware-documentation/pull/424.
Current map design doc include a specific guideline for how to divide maps for Autoware, which seems to be out of the scope of the design doc. Furthermore, the same description is included in the readme in Autoware Universe, making it more difficult to maintain both documentation properly.
Thus, I'd like to remove the specific description in Autoware Documentation and put a link to readme instead.
One of the alternatives would be to leave this documentation as it is, and put the link to this page in Readme instead. However, given that the most of the package description is included in Readme and not in Documentation page, I'd like to take the former approach to be consistent with other packages.
The PR …
> feat: remove description about divided maps and put link instead

- docs/design/autoware-architecture/planning/index.md
"Behavior Planner" calculates "path", not "trajectory", so I corrected
#427 
> docs: fix the typo (trajectory -> path).

- docs/reference-hw/full_drivers_list.md
- docs/reference-hw/lidars.md
This PR adds links to the Nebula sensor driver to relevant supported reference hardware (Velodyne and Hesai).
This is the driver currently employed by default in Autoware Universe (see https://github.com/autowarefoundation/autoware/pull/3699).
> docs(reference-hw): add nebula

- docs/contributing/coding-guidelines/ros-nodes/parameters.md
This PR recovers the details about the types of parameter files exist in Autoware system that was deleted in [this PR.](https://github.com/autowarefoundation/autoware-documentation/pull/367) 
> feat(parameters.md): update deatils about the types of parameter files

- docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
fix: add rosbag replay option "--clock" to be activate time triggerd sub-modules, such as the lateral control module
> fix: add rosbag replay option "--clock"

- docs/contributing/coding-guidelines/ros-nodes/parameters.md
> docs: update parameters.md coding guidelines

- docs/installation/autoware/source-installation.md
Belongs to [Standardize a strategy for packages with downloaded artifacts](https://github.com/orgs/autowarefoundation/discussions/3649)
Add information about manual downloading packages artifacts if ansible isn't used. 
See https://github.com/autowarefoundation/autoware.universe/issues/3137
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request …
> docs(installation): add link to manual artifacts downloading instruction

- docs/design/autoware-architecture/sensing/data-types/point-cloud.md
* I noticed that the lidar data filed types presented on this page do not match the actual ones. So, I fixed them.
|type| before | after|reference
|--|--|--|--|
|T(time)|FLOAT32|FLOAT64| [distortion_corrector.cpp](https://github.com/autowarefoundation/autoware.universe/blob/a3e87cc537554e18732c0ebd86ae39d7b9d14a85/sensing/pointcloud_preprocessor/src/distortion_corrector/distortion_corrector.cpp#L195)|
|I(intensity)|UINT8|FLOAT32| [ring_outlier_filter.cpp](https://github.com/autowarefoundation/autoware.universe/blob/a3e87cc537554e18732c0ebd86ae39d7b9d14a85/sensing/pointcloud_preprocessor/src/outlier_filter/ring_outlier_filter_nodelet.cpp#L96)|
* Also, I found some nodes require the time_stamp as *seconds* rather than *nanoseconds*.
e.g. …
> docs(sensing): update lidar data field requirement

- docs/how-to-guides/others/using-divided-map.md
Add new page for using split maps to enable dynamic map loading feature.
> feat: add split map tutorial

- docs/contributing/pull-request-guidelines/ci-checks.md
Add word registration guidelines for spell check.
> docs(ci-checks): add word registration guidelines for spell check

- docs/contributing/pull-request-guidelines/index.md
Add note of updating pull request branch.
> docs(pull-request-guidelines): add note of updating pull request branch

- docs/how-to-guides/integrating-autoware/launch-autoware/localization/index.md
I added a note to users who use pose_estimator other than NDT.
> docs(localization): add note for non-NDT users

- docs/contributing/coding-guidelines/ros-nodes/directory-structure.md
> fix(directory-structure): update reference url

- docs/installation/autoware/source-installation.md
- docs/tutorials/ad-hoc-simulation/planning-simulation.md
- docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
> fix: !!! info notation correction

- docs/how-to-guides/others/advanced-usage-of-colcon.md
Default ccache size is 5GB but as users keep rebuilding different things, it can go up to 40GB in size.
So I set 60GB limit for the ccache config file and made sure it is in the correct place. (Ubuntu 22.04 default is in `.cache/ccache`)
> feat: improve ccache documentation with config

- docs/design/autoware-interfaces/ad-api/.pages
- docs/design/autoware-interfaces/ad-api/features/routing.md
- docs/design/autoware-interfaces/ad-api/list/api/fail_safe/mrm_state.md
- docs/design/autoware-interfaces/ad-api/list/api/perception/objects.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/dimensions.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/kinematics.md
- docs/design/autoware-interfaces/ad-api/list/index.md
- docs/design/autoware-interfaces/ad-api/release.md
- tools/autoware-interfaces/generate.py
Update AD API documents for v1.1.0 release.
- Add release notes page
- Add first release version to API list page
- Add "[v1.1.0]" to route option section.
- Update release status of v1.1.0 APIs
> docs(ad-api): release v1.1.0

- docs/installation/autoware/docker-installation.md
Fix run.sh documentation that being used in the Open AD Kit.
> docs(installation): fix run.sh documentation

- .markdownlint.yaml
- docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
This PR is one of group of PRs that aim to fix Autoware logging system to achieve the goal of reducing excessive error and warning logs on Autoware launch. 
Part of:
- https://github.com/autowarefoundation/autoware.universe/issues/5539
> docs(rosbag-replay-simulation): add warnings about timestamp discrepancies and pre-playback messages

- docs/tutorials/ad-hoc-simulation/digital-twin-simulation/.pages
- docs/tutorials/ad-hoc-simulation/digital-twin-simulation/carla-tutorial.md
Add the Carla simulator page, which includes several projects able to bridge Autoware and Carla.
> docs: add the carla simulator page under digital twin

- docs/design/autoware-interfaces/ad-api/list/api/vehicle/doors/command.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/doors/layout.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/doors/status.md
- docs/design/autoware-interfaces/ad-api/list/index.md
- docs/design/autoware-interfaces/ad-api/release.md
- docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/MrmState.md
Update AD API documents for v1.2.0 release. See release note page for details.
> docs(ad-api): release v1.2.0

- docs/contributing/coding-guidelines/ros-nodes/coordinate-system.md
- docs/contributing/index.md
- docs/design/autoware-concepts/difference-from-ai-and-auto.md
- docs/design/autoware-interfaces/components/vehicle-interface.md
- docs/design/autoware-interfaces/templates/autoware-data-type.jinja2
- docs/design/autoware-interfaces/templates/autoware-interface.jinja2
- docs/how-to-guides/integrating-autoware/creating-maps/creating-vector-map/index.md
- docs/how-to-guides/integrating-autoware/creating-maps/creating-vector-map/lanelet2/index.md
- docs/how-to-guides/integrating-autoware/creating-maps/open-source-slam/lio-sam/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/calibration-tools/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/ground-lidar-calibration/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/lidar-camera-calibration/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/lidar-lidar-calibration/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-vehicle-model/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/index.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-interface-package/creating-vehicle-interface.md
- docs/how-to-guides/integrating-autoware/launch-autoware/index.md
- docs/how-to-guides/integrating-autoware/launch-autoware/localization/index.md
- docs/how-to-guides/integrating-autoware/overview.md
- docs/how-to-guides/others/defining-temporal-performance-metrics.md
- docs/index.md
- docs/installation/index.md
- docs/tutorials/scenario-simulation/planning-simulation/installation.md
- main.py
Fix a warning for relative links when generating documentation. Below are some of the warnings.
```
$ mike deploy HEAD
...
INFO    -  Doc file 'how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/lidar-lidar-calibration/index.md' contains an unrecognized relative link
'../extrinsic-manual-calibration', it was left as is. Did you mean '../extrinsic-manual-calibration/index.md'?
INFO    -  Doc file 'how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/lidar-lidar-calibration/index.md' contains an unrecognized relative link
'../extrinsic-manual-calibration', it was left as is. Did you mean '../extrinsic-manual-calibration/index.md'?
INFO    -  Doc file 'how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model …
```
> fix: warning for relative links

- docs/installation/autoware/source-installation.md
In a previous PR, I've removed the CUDA step from the manual instructions by mistake, this PR brings it back.
Also adding the ansible installation to the list which is going to be added in this PR:
- https://github.com/autowarefoundation/autoware/pull/4675
> fix: update manual installation instructions

- docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Part of:
- https://github.com/autowarefoundation/autoware/issues/4659
Please follow the instructions on
- https://autowarefoundation.github.io/AWSIM/main/GettingStarted/QuickStartDemo/
to test AWSIM Labs with the Autoware and provide feedback!
> feat: add awsim labs documentation reference

- docs/contributing/coding-guidelines/ros-nodes/class-design.md
- docs/contributing/coding-guidelines/ros-nodes/directory-structure.md
- docs/contributing/coding-guidelines/ros-nodes/parameters.md
Previous discussions:
- https://github.com/autowarefoundation/autoware/issues/4569
- https://github.com/orgs/autowarefoundation/discussions/4097
As we are prefixing the packages with `autoware_`, we needed to clear the rules to avoid confusion.
Using or omitting the `autoware_` prefix or `_node` suffix can be highly confusing without clear guidelines. …
> feat: update the naming rules for directories and classes

- docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Reflects the repo name change from "AWSIM" to "AWSIM-Labs"
> fix: awsim-labs link

- docs/how-to-guides/integrating-autoware/overview.md
According to autoware.repos, the structure is as follows:
YOUR_SENSOR_KIT_**launch**/
├── YOUR_SENSOR_KIT_description/
└── YOUR_SENSOR_KIT_launch/
Made changes because the documentation described the structure as follows before the changes:
YOUR_SENSOR_KIT_**description**/
├── YOUR_SENSOR_KIT_description/
└── YOUR_SENSOR_KIT_launch/ …
> fix: to improve the readability of the documentation, unified the name of the sensor_kit repository to YOUR_SENSOR_KIT_launch

- docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
This updates the download link for rosbag to the one with autoware_msgs instead of autoware_auto_msgs
Related link: https://github.com/orgs/autowarefoundation/discussions/3862
> feat: update rosbag file for autoware_msgs

- docs/contributing/pull-request-guidelines/.pages
- docs/contributing/pull-request-guidelines/ai-pr-review.md
Add docs for the PR Agent workflow.
> feat: add ai pr review docs

- docs/support/support-guidelines.md
I've made a lot of improvements on the support-guidelines page of the documentation.
> feat(support-guidelines): update guidelines for Autoware community support

- docs/design/autoware-architecture/sensing/data-types/point-cloud.md
This PR updates the pointcloud type documentation to be consistent with recent changes in Autoware.
For background:
https://github.com/orgs/autowarefoundation/discussions/3533
https://github.com/orgs/autowarefoundation/discussions/3578
Related Autoware PRs:
https://github.com/autowarefoundation/autoware.universe/pull/6996
https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/94
[pull request …
> docs(sensing): update pointcloud type information

- docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
There was a mistake when I updated the link for rosbags during migration from autoware_auto_msgs to autoware_msgs in https://github.com/autowarefoundation/autoware-documentation/pull/563
Users cannot download the rosbag with gdown with the current link.
This PR will fix that issue.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelin …
> fix(rosbag-replay-simulation): fix link for gdown

- docs/design/autoware-interfaces/ad-api/list/api/routing/change_route.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/change_route_points.md
- docs/design/autoware-interfaces/ad-api/list/index.md
- docs/design/autoware-interfaces/ad-api/release.md
Update AD API documents for v1.5.0 release. [See release note page for details.](https://autowarefoundation.github.io/autoware-documentation/pr-595/design/autoware-interfaces/ad-api/release/)
Related link: https://github.com/autowarefoundation/autoware.universe/pull/8267
> docs(ad-api): release adapi v1.5.0

- docs/contributing/coding-guidelines/ros-nodes/directory-structure.md
- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/index.md
This PR is a counterpart of https://github.com/autowarefoundation/autoware.universe/pull/8323 in autoware.universe.
The URL to gnss_poser is revised since the package name will change.
**This PR should be merged after merging https://github.com/autowarefoundation/autoware.universe/pull/8323.**
Plus, I also wrote a caution that the example in directory-structure doesn't match the actual gnss_poser package.
**TODO**: Rename class name and file name in gnss_poser in autoware.universe to match the example.
- gnss_poser_core.cpp/hpp -> gnss_poser_node.cpp/hpp
- autoware::gnss_poser::GNSSPoser -> autoware::gnss_poser::GNSSPoserNode
The PR author **must** …
> chore: add autoware_ prefix to the URL of gnss_poser

- docs/contributing/coding-guidelines/ros-nodes/class-design.md
- docs/contributing/coding-guidelines/ros-nodes/directory-structure.md
- docs/how-to-guides/integrating-autoware/launch-autoware/index.md
[In the coding guidelines, autoware_gnss_poser is used as an example](https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/ros-nodes/directory-structure/).
However, there are some lines that mismatch to the actual [`autoware_gnss_poser`](https://github.com/autowarefoundation/autoware.universe/tree/main/sensing/autoware_gnss_poser), so I fixed them in this PR. …
> chore(coding_guidelines): match the example to the actual autoware_gnss_poser

- docs/contributing/coding-guidelines/index.md
- docs/contributing/coding-guidelines/languages/cpp.md
Updated the coding guideline.
To the reviewers:
- Please check whether there are any inappropriate guidelines included.
- In particular, verify if my thoughts on new/delete/free/raw pointers and throw are correct.
- If there are any other points that should be mentioned, please let me know. I'd like to add anything that can be easily incorporated.
- Please confirm if the structure of the text, the subtitles, and the paragraph divisions are appropriate.
- Regarding the ROS nodes guidelines in the ROS 2 Style Guide, I'm not sure where the link should point to, so I've linked it to class-design.md. If there is a better option, please let me know.
- Since I think that the coding guideline document is still incomplete, I have left the "Under Construction" note. Please let me know if it should …
> docs(contributing): update the coding guideline

- docs/design/autoware-interfaces/ad-api/use-cases/change-operation-mode.md
- docs/design/autoware-interfaces/ad-api/use-cases/drive-designated-position.md
- docs/design/autoware-interfaces/ad-api/use-cases/get-on-off.md
- docs/design/autoware-interfaces/ad-api/use-cases/initialize-pose.md
- docs/design/autoware-interfaces/ad-api/use-cases/launch-terminate.md
- docs/design/autoware-interfaces/ad-api/use-cases/sequence/drive-designated-position.plantuml
Fix adapi use case page links.
> fix: fix adapi usecase links

- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/index.md
This PR adds a sample Robosense launch with nebula for users.
Related: https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/102
> docs: add example robosense Bpearl launch

- docs/how-to-guides/integrating-autoware/launch-autoware/localization/index.md
- docs/how-to-guides/others/an-example-procedure-for-adding-and-evaluating-a-new-node.md
This PR will change the github link of `ndt_scan_matcher` due to the change in https://github.com/autowarefoundation/autoware.universe/pull/8904 .
This PR should be merged after merging the https://github.com/autowarefoundation/autoware.universe/pull/8904 in autoware.universe.
> fix: update github link of ndt_scan_matcher

- docs/how-to-guides/integrating-autoware/launch-autoware/localization/index.md
- docs/how-to-guides/others/an-example-procedure-for-adding-and-evaluating-a-new-node.md
This PR will fix the broken link in the docs.
> fix: update github link

- docs/installation/autoware/docker-installation.md
- docs/installation/autoware/source-installation.md
Added missing instructions to the following guides:
* Docker update
* Source install
* Source update
Specifically, `sudo apt update && sudo apt upgrade` were missing: `rosdep update` and `rosdep install` will not upgrade previously installed `ros-$ROS_DISTRO-*` packages (even when Autoware is expected to be built with newer versions), which often results in unexpected Autoware build failures.
From my experience in the last two weeks, following the instructions perfectly on a clean Autoware repo succeeded one out of five times mainly due to this issue.
I also added comments that for moved/removed dependencies in the `repos` files, `vcstool` will not sync correctly and result in duplicate or wrongly remaining packages, in which case the `src` directory has to be deleted and re-pulled.
The …
> docs: add apt update/upgrade to workspace install/update instructions

- docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
> docs(awsim-tutorial): update the awsim labs comparison table

- docs/tutorials/ad-hoc-simulation/digital-twin-simulation/carla-tutorial.md
Added autoware_carla_interface as one of the project in carla tutorial.
> docs: added autoware_carla_interface package in carla tutorial

- docs/design/autoware-interfaces/ad-api/features/routing.md
- docs/design/autoware-interfaces/ad-api/list/api/routing/clear_route.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/doors/command.md
- docs/design/autoware-interfaces/ad-api/list/api/vehicle/status.md
- docs/design/autoware-interfaces/ad-api/release.md
- docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/RouteOption.md
- yaml/autoware-interfaces.yaml
Add restrictions and options for safety. Related to https://github.com/autowarefoundation/autoware_adapi_msgs/pull/61.
See the [release notes](https://autowarefoundation.github.io/autoware-documentation/pr-602/design/autoware-interfaces/ad-api/release/) for v1.6.0 for details. 
> feat(ad-api): add restrictions and options

- docs/tutorials/scenario-simulation/planning-simulation/random-test-simulation.md
- docs/tutorials/scenario-simulation/planning-simulation/scenario-test-simulation.md
When using `scenario_simulator_v2`, for the latest Autoware, it is preffeered to specify `awf/universe/20240605` as the launch argument `architecture_type`.
The `architecture_type` parameter of `scenario_simulator_v2` is mainly used to switch traffic light messages, which change frequently in recent Autoware.
For more details, see https://github.com/tier4/scenario_simulator_v2/pull/1277.
This is related to issue below
- https://github.com/tier4/scenario_simulator_v2/issues/1374
[contribution guidelines]: …
> docs: fix `architecture_type` for scenario_simulator_v2

- docs/contributing/testing-guidelines/integration-testing.md
- docs/design/autoware-architecture/map/index.md
- docs/how-to-guides/integrating-autoware/creating-maps/pointcloud-map-downsampling/index.md
- docs/how-to-guides/others/using-divided-map.md
This PR will add autoware prefix to `map_loader` due to the change in https://github.com/autowarefoundation/autoware.universe/pull/8927 .
This PR should be merged after https://github.com/autowarefoundation/autoware.universe/pull/8927 merged .
> fix: add autoware prefix to the map_loader

- docs/installation/autoware/docker-installation.md
- docs/installation/autoware/source-installation.md
- https://github.com/autowarefoundation/autoware/pull/5440
Has introduced the `autoware-nightly.repos`.
This PR adds this relevant information to the installation guides.
> docs(installation): add information about nightly.repos

- docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/creating-sensor-model/index.md
This PR will add the autoware prefix to pointcloud_preprocessor due to the changes in https://github.com/autowarefoundation/autoware.universe/pull/7983 .
> fix: add autoware_ prefix to pointcloud_preprocessor

- docs/tutorials/components_evaluation/localization_evaluation/urban-environment-evaluation.md
There are some broken links in "Tutorials>>ComponentsEvaluation>>UrbanEnvironmentEvaluation" [Documentation](https://autowarefoundation.github.io/autoware-documentation/main/tutorials/components_evaluation/localization_evaluation/urban-environment-evaluation/). This PR update these links.
1. The video links appear to be broken. I have updated these broken video links.
New links for same videos are here:
[video-1](https://youtu.be/6On130bjQUY?si=RBB28OLLbplV7j2i)
[video-2](https://youtu.be/DQsk3rY7NjY?si=57xvN_5tPelCdfU1)
2. Drive link is updated. Updated lİnk is [here](https://drive.google.com/drive/folders/1ges_2q8qljgLfwjZbv2Bn35Rv5awhd_U?usp=sharing)
None.
None.
> fix: update dead links

- docs/design/autoware-interfaces/ad-api/release.md
Update AD API documents for v1.7.0 release. [See release note page for details.](https://autowarefoundation.github.io/autoware-documentation/pr-646/design/autoware-interfaces/ad-api/release/)
None
None.
None.
> docs(ad-api): release adapi v1.7.0

- docs/installation/autoware/docker-installation.md
Update run command for docker containers with respect to CI changes addressed in https://github.com/autowarefoundation/autoware/pull/5830 and https://github.com/autowarefoundation/autoware/pull/5831.
We can merge it after `autoware:universe-cuda` deployment and confirmation that it already inherits `autoware-base:cuda-latest` with changes from https://github.com/autowarefoundation/autoware/pull/5830.
None.
> docs: add artifacts path to run command

- docs/installation/autoware/docker-installation.md
- docs/installation/autoware/source-installation.md
This PR adds documentation on how to download the extra repositories now that `tamagawa_imu_driver` and `pacmod_interfaces` are not downloaded automatically from the `autoware.repos` file.
See https://github.com/autowarefoundation/autoware/issues/3366
None.
None.
> refactor: added documentation about the extra packages

- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/acceleration.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/gear.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/hazard_lights.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/pedals.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/steering.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/turn_indicators.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/command/velocity.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/control_mode/list.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/control_mode/select.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/control_mode/status.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/local/operator/heartbeat.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/acceleration.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/gear.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/hazard_lights.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/pedals.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/steering.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/turn_indicators.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/command/velocity.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/control_mode/list.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/control_mode/select.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/control_mode/status.md
- docs/design/autoware-interfaces/ad-api/list/api/manual/remote/operator/heartbeat.md
- docs/design/autoware-interfaces/ad-api/list/index.md
- docs/design/autoware-interfaces/ad-api/release.md
Update AD API documents for v1.8.0 release. See [release note page](https://github.com/isamu-takagi/autoware-documentation/blob/feat/adapi-v1.8.0/docs/design/autoware-interfaces/ad-api/release.md) for details.
None
None.
None.
> docs(ad-api): release adapi v1.8.0

- docs/design/autoware-interfaces/ad-api/features/control.md
- docs/design/autoware-interfaces/ad-api/features/vehicle-status.md
- docs/design/autoware-interfaces/ad-api/list/api/control/command/acceleration.md
- docs/design/autoware-interfaces/ad-api/list/api/control/command/pedals.md
- docs/design/autoware-interfaces/ad-api/list/api/control/command/steering.md
- docs/design/autoware-interfaces/ad-api/list/api/control/command/velocity.md
- docs/design/autoware-interfaces/ad-api/list/index.md
The name "vehicle command" is confusing with the actual value of the vehicle.
This API is a target value, so rename it to "control command" before release.
None
None.
None.
> feat(ad-api): rename control command api

- docs/design/autoware-concepts/.pages
- docs/design/autoware-concepts/index.md
This updates the Autoware Concepts page to describe Autoware's design concepts.
I also removed the difference-from-ai-and-auto.md page from index from concepts page now. It's quite old page and is not really explaining about the concepts so much. I'm planning to create a page for "past releases". and I can re-add the explanation about Autoware AI and Autoware Auto under that section.
None.
None.
> feat: update Autoware Concepts page
