.pre-commit-config.yaml, mkdocs.yaml
https://squidfunk.github.io/mkdocs-material/reference/diagrams/
=> chore: add mermaid

.github/workflows/delete-closed-pr-docs.yaml, .github/workflows/deploy-docs.yaml, .github/workflows/sync-files.yaml
Related: https://github.com/autowarefoundation/autoware/pull/74
=> ci: use v1 instead of tier4/proposal

.github/workflows/delete-closed-pr-docs.yaml, .github/workflows/sync-files.yaml
Same as https://github.com/autowarefoundation/autoware/pull/75.
=> ci: change cron schedules

.github/workflows/deploy-docs.yaml
Apply https://github.com/autowarefoundation/autoware-github-actions/pull/93.
=> ci: add an alias from 'main' to 'latest'

docs/contributing/testing-guidelines/testing-in-general.md
[This PR is for discussion only]
@kenji-miyake 
I have modified the structure of `testing-in-general`.
Added explanation to the unit testing section and changed the position of the Reference section.
We have also discussed the chapter structure, but I think it is fine as it is now.
Signed-off-by: Keisuke Shima <19993104+KeisukeShima@users.noreply.github.com>
=> wip: update testing-in-general

docs/installation/autoware/docker-installation.md, docs/installation/autoware/source-installation.md
Added a warning for the Docker setup script as well.
=> docs(installation): add a warning for the Docker setup script

docs/installation/autoware/docker-installation.md
Added a warning for the NVIDIA Deep Learning Container license.
The Autoware Universe images are based on CUDA images.
=> docs(installation): add a warning for NVIDIA Deep Learning Container license

docs/help/docs-guide.md, docs/help/index.md, docs/index.md
Updated help pages.
I wrote minimal information for now.
=> docs(help): update help pages

docs/installation/autoware/source-installation.md
This PR adds manual installation steps for source installation.
=> docs(source-installation): add manual installation steps

docs/contributing/pull-request-guidelines/.pages, docs/contributing/pull-request-guidelines/review-guidelines.md, docs/help/troubleshooting.md, docs/how-to-guides/index.md
=> docs: fix invalid links

docs/help/troubleshooting.md
Generally, there is no need to uninstall packages.
I've confirmed this [here](https://github.com/autowarefoundation/autoware/pull/154#issuecomment-1091061287).
=> docs: update CUDA troubleshooting

docs/installation/autoware/docker-installation.md
Updates for https://github.com/autowarefoundation/autoware/pull/241.
=> docs(docker-installation): update manual installation steps

docs/installation/autoware/docker-installation.md, docs/installation/autoware/source-installation.md
Signed-off-by: Shumpei Wakabayashi <shumpei.wakabayashi@tier4.jp>
Related issue: https://github.com/autowarefoundation/autoware/issues/263
In order to update repos, we should command
```
vcs import src < autoware.repos
vcs pull src
```
=> docs(installation): fix how to update repos

.markdown-link-check.json, docs/contributing/index.md, docs/index.md
Signed-off-by: IshitaTakeshi <ishitah.takeshi@gmail.com>
Fix broken link 
=> docs: fix broken link

docs/contributing/coding-guidelines/ros-nodes/.pages, docs/contributing/coding-guidelines/ros-nodes/message-guidelines.md
Signed-off-by: M. Fatih Cırıt mfc@leodrive.ai
I've decided to put this here instead. This way other message repos can benefit from this too.
=> docs(message-guidelines): add message guidelines

docs/design/autoware-interfaces/general/absorb-changes.drawio.svg, docs/design/autoware-interfaces/general/architecture.drawio.svg, docs/design/autoware-interfaces/general/hierarchy.drawio.svg, docs/design/autoware-interfaces/general/new-feature.drawio.svg, docs/design/autoware-interfaces/general/unified-access.drawio.svg, docs/design/autoware-interfaces/index.md
Add the document of Autoware interface design. 
https://github.com/autowarefoundation/autoware/discussions/41
=> docs(autoware-interfaces): add autoware interface design

docs/support/troubleshooting.md
Added some additional troubleshooting tips based on recent Q&A discussions, and reformatted some of the existing guide.
Signed off by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>
=> docs: update troubleshooting guide

docs/support/troubleshooting.md
Remove dead link to pass the pre-commit-optional CI.
=> fix(support): remove dead link

.github/workflows/github-release.yaml, docs/installation/autoware/docker-installation.md
Signed-off-by: Shark Liu <huiyuan.liu@autocore.ai>
Solve #112 
Update docker installation chapter with arm64 architecture platform.
=> docs(installation): add arm64 docker installation

docs/contributing/coding-guidelines/ros-nodes/message-guidelines.md, docs/how-to-guides/advanced-usage-of-colcon.md, docs/how-to-guides/how-to-integrate-autoware-with-your-vehicle.md, docs/installation/autoware/docker-installation.md, docs/installation/autoware/source-installation.md
`ROS 2` is the official notation.
https://docs.ros.org/en/rolling/index.html
=> docs: replace "ROS2" with "ROS 2"

docs/tutorials/scenario-simulation/planning-simulation/random-test-simulation.md
Update broken link in random-test-simulation.md
This issue has discussed in #118 
=> docs(tutorial): update broken link in random-test-simulation.md

docs/support/troubleshooting.md
I got an error during launching Autoware.
So I've updated the troubleshooting guide.
Related: https://github.com/autowarefoundation/autoware/discussions/204#discussioncomment-2934553
Note: The words `Runtime errors` are replaced by `Runtime issues` to be consistent with other sections.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guid …
=> docs(troubleshooting): add multicast settings

docs/how-to-guides/index.md, docs/how-to-guides/sensor-calibration.md
Signed-off-by: mitsudome-r <ryohsuke.mitsudome@tier4.jp>
Add how-to-guides for sensor calibration.
Related issue: https://github.com/autowarefoundation/autoware.universe/issues/679
This PR is meant to create a page for sensor calibration so that members of AWF can start adding their calibration tools.
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/p …
=> docs(how-to-guides): add instructions for sensor calibration

docs/how-to-guides/sensor-calibration.md
Signed-off-by: JianKang <egon.kang@autocore.ai>
Refer to issue [679](https://github.com/autowarefoundation/autoware.universe/issues/679) 
=> docs(how-to): add lidar imu calibration guide

docs/design/autoware-interfaces/ad-api/list/api/fail_safe/index.md, docs/design/autoware-interfaces/ad-api/list/api/fail_safe/state.drawio.svg, docs/design/autoware-interfaces/ad-api/list/api/fail_safe/state.md, docs/design/autoware-interfaces/ad-api/list/index.md, docs/design/autoware-interfaces/ad-api/types/autoware_ad_api_msgs/msg/fail_safe_state.md
=> docs(ad-api): add fail safe api

docs/how-to-guides/sensor-calibration.md
Update the link of li-calib calibration tool from personal repo to Autocore official github repo.
=> docs: update link of lidar imu calibration tool

docs/support/troubleshooting.md
See https://github.com/autowarefoundation/autoware/pull/2766.
=> fix(troubleshooting): update commands for autowarefoundation/autoware#2766

docs/contributing/documentation-guidelines/index.md
Signed-off-by: Lalith Vipulananthan <lalith.vipulananthan@tier4.jp>
An initial attempt at adding more detail to the documentation guidelines. I think there is room for improvement, so any feedback or comments would be greatly appreciated. 
For example, are there any problems that have come up in previous documentation PRs where there has been a style mismatch? I included some links to specific style points that I think should be included (eg: sentence case and US spelling), but I'm sure that there are some points that I have missed out.  
After all checkboxes are checked, anyone who has …
=> feat: improve documentation guidelines

docs/contributing/documentation-guidelines/index.md, docs/design/autoware-architecture/node-diagram/index.md, docs/how-to-guides/creating-maps-for-autoware.md
=> fix(node-diagram): fix image link

docs/how-to-guides/calibrating-your-sensors.md
Signed-off-by: JianKang <egon.kang@autocore.ai>
This calibration was recently developed by Autocore and open-sourced.
=> docs: add lidar-lidar calibration tool 

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Signed-off-by: Wojciech Jaworski <wojciech.jaworski@robotec.ai>
=> docs(tutorial): awsim instruction fixes

docs/contributing/index.md, docs/contributing/pull-request-guidelines/commit-guidelines.md
Applied minor fixes.
I'll add supplemental information using inline comments.
=> style: apply minor fixes

mkdocs.yaml
=> build(mkdocs.yaml): set toc_depth to 3

docs/design/autoware-interfaces/components/vehicle-dimensions.md
Fix  description of base link.
https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-architecture/localization/#tf-tree
=> docs(autoware-interfaces): fix description of base link

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Signed-off-by: Wojciech Jaworski <wojciech.jaworski@robotec.ai>
=> docs(tutorial): awsim prerequisites

docs/installation/autoware/docker-installation.md, docs/installation/autoware/source-installation.md
=> feat(installation): add humble information

docs/.pages, docs/datasets/.pages, docs/datasets/index.md, docs/index.md
This PR adds a datasets section to the documentation page.
=> docs(datasets): add datasets section

docs/contributing/pull-request-guidelines/ci-checks.md, docs/contributing/pull-request-guidelines/index.md
Update the pull request guidelines.
Related: https://github.com/orgs/autowarefoundation/discussions/2816#discussioncomment-3505416
Depends on https://github.com/autowarefoundation/autoware-documentation/pull/193.
=> feat(pull-request-guidelines): update descriptions

docs/design/autoware-architecture/planning/index.md
Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>
add specific road cases which are supported
=> feat: add supported specific road cases

docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
We need to specify storage option if metadata.yaml does not exist since humble.
=> fix(rosbag-replay-simulation): add storage option for rosbag play

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Signed-off-by: Wojciech Jaworski <wojciech.jaworski@robotec.ai>
=> docs(tutorial): awsim oss instruction

docs/design/autoware-interfaces/components/vehicle-dimensions.md
Addressed spelling issues found in https://github.com/autowarefoundation/autoware-documentation/actions/runs/3208792151.
Some words are added to https://github.com/tier4/autoware-spell-check-dict.
Also, before that, the wrong structures of the bullet lists are fixed in ec2f0cf5abdc701f28a2806e2de02a81217af124.
Before:
After: …
=> fix(vehicle-dimensions): fix cspell issues

docs/how-to-guides/applying-clang-tidy-to-ros-packages.md, docs/how-to-guides/index.md
Add a brief manual of Clang-Tidy.
=> feat(how-to guides): add clang-tidy how-to

docs/contributing/coding-guidelines/languages/cpp.md
Add guideline for C++.
Related to https://github.com/autowarefoundation/autoware/discussions/2824.
=> feat(coding-guidelines): add guideline for C++

docs/how-to-guides/calibrating-your-sensors.md
Signed-off-by: Ram [ram@interpl.ai](mailto:ram@interpl.ai)
=> docs: update sensor-calibration.md

README.md
=> docs(readme): add link to the contribution guidelines

docs/installation/additional-settings-for-developers/index.md
Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>
I would like to add DDS settings for beginners to execute Autoware as they expect. They tend to execute Autoware without taking care of DDS settings. It causes performance problem which cannot seen on Rviz.
Some of beginners reported that sensing pre-processing runs at less than 10 Hz, it is not expected (https://github.com/tier4/CARET_analyze/issues/155#issuecomment-1275625569). One of them gave me a figure which shows  this unexpected behavior. It is a time-series graph plotting frequency of callback execution in `/sensing/lidar/top/velodyne_convert_node`. The frequency decreased time by time and below 10 Hz.
Tackling this issue with him, I found that default receive buffer size is so small that Autoware cannot receive large …
=> docs(installation): add DDS setting to additional-settings-for-developpers

docs/installation/autoware/docker-installation.md
Signed-off-by: Maxime CLEMENT <maxime.clement@tier4.jp>
Following the documentation for the [Docker installation](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/docker-installation/) from a fresh Ubuntu install currently does not work (see https://github.com/autowarefoundation/autoware/issues/2821#).
The issue is caused by Nvidia and cuda drivers being required on the host machine in order to run the Docker image.
Currently, the dependencies installed automatically, as well as the [instructions to install them manually](https://autowarefoundation.github.io/autoware-documentation/main/installation/autoware/docker-installation/#installing-dependencies-manually), are missing the required Nvidia and cuda drivers.
This PR add cuda to the list of manual …
=> docs(docker-install): add CUDA to "Installing dependencies manually"

docs/design/autoware-architecture/node-diagram/index.md, main.py
See https://github.com/tier4/autoware-documentation/pull/16.
=> refactor: use macros for drawio images

.github/workflows/deploy-docs.yaml
To keep documents of old versions.
=> ci(deploy-docs): add galactic to deploy-docs's target

docs/tutorials/ad-hoc-simulation/planning-simulation.md, docs/tutorials/ad-hoc-simulation/rosbag-replay-simulation.md
Add planning simulation reference video link.
=> docs(tutorial): add planning simulation reference video

docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/localization_initialization_state.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/motion_state.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/mrm_state.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/operation_mode_state.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/response_status.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_data.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_primitive.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_segment.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/route_state.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/steering_factor.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/steering_factor_array.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/velocity_factor.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/velocity_factor_array.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/accept_start.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/change_operation_mode.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/clear_route.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/initialize_localization.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/set_route.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/set_route_points.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_version_msgs/srv/interface_version.md
Add reverse reference of message.
=> feat(ad-api): add reverse reference of message

docs/how-to-guides/calibrating-your-sensors.md
Provide a new tool for lidar-camera calibration by AutoCore
=> feat(how-to-guides): add a new lidar-camera-calibration tool

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Signed-off-by: wjaworski <wojciech.jaworski@robotec.ai>
=> docs(tutorial): awsim ros2 humble note

docs/contributing/coding-guidelines/ros-nodes/console-logging.md
Suggestions for improvements to #216.
Resolves #212
=> feat: add console-logging doc

docs/how-to-guides/.pages, docs/how-to-guides/fixing-dependent-package-versions.md
Add how to fix the dependent package versions and the package version currently developing
=> docs(how-to-guides): add how to fix dependent package versions

docs/how-to-guides/index.md
=> docs(how-to-guides): reference fixing-dependent-package-versions.md

docs/how-to-guides/creating-maps-for-autoware/open-source-slam/hdl-graph-slam/index.md
Signed-off-by: Yukihiro Saito <yukky.saito@gmail.com>
Fix dead link in hdl_graph_slam page
Please merge after [this PR](https://github.com/koide3/hdl_graph_slam/pull/253)
=> fix(how-to-guides/creating-maps-for-autoware): dead link in hdl_graph_slam page

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Signed-off-by: wjaworski <wojciech.jaworski@robotec.ai>
=> docs(tutorial): removed temporary note

docs/installation/autoware/docker-installation-devel.md
Signed-off-by: AhmedEbrahim <ahmed.a.d.ebrahim@gmail.com>
closes #303 
=> fix(docker-installaion-devel): rocker does not show any progress for image pull

docs/how-to-guides/debug-autoware.md
Adding some simple but useful debug tips.
=> docs(how-to-guides): add ros2_graph and ros2doctor to debug guidelines

docs/installation/autoware/docker-installation-devel.md
This PR is to fix a minor typo
=> fix: typo fix in the autoware installation documentation

docs/contributing/coding-guidelines/ros-nodes/parameters.md
Signed-off-by: kminoda <koji.minoda@tier4.jp>
=> feat: add parameter description

docs/installation/additional-settings-for-developers/index.md, docs/support/troubleshooting.md
The documentation around the network was expanded because many people get stuck due to insufficient documentation.
I also corrected duplicate descriptions and wrong links.
=> feat(installation, troubleshooting): update network settings

docs/design/autoware-architecture/planning/index.md
Added a explanation of a part of important planning parameters
=> feat: add a part of important planning parameters' explanation

docs/support/troubleshooting.md
Add a runtime issue troubleshooting.
=> docs(support/troubleshooting): add a runtime issue troubleshooting

docs/design/autoware-architecture/map/index.md
Add map design documentation. For now I would like to add pointcloud map interface information. The other documentation shall be added later on.
=> docs: add map design document

mkdocs.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/3620#discussion_r1184574496.
=> build(mkdocs.yaml): include GIF files

mkdocs.yaml
It's a convention to update the copyright year.
Answer by ChatGPT:
> Updating the copyright year on a website to the latest single year serves several purposes. It is not a legal requirement, but it can have practical benefits. Here are a few reasons to update the copyright year:
Perception of freshness: When visitors see the current year in the copyright notice, it gives the impression that the website is up-to-date and well-maintained. An outdated copyright year might suggest that the site's content is not regularly updated, which could potentially discourage users from engaging with the site.
Protecting your content: Although copyright protection automatically applies to original works upon creation, displaying an updated copyright notice may help to deter content theft. It signals to …
=> build(mkdocs.yaml): update copyright year

mkdocs.yaml
See https://github.com/autowarefoundation/autoware.universe/pull/3622/files#r1184770192.
`md_in_html` was added in https://github.com/autowarefoundation/autoware.universe/pull/1299.
Related: https://squidfunk.github.io/mkdocs-material/reference/images/#configuration
=> build(mkdocs.yaml): sync extensions with autoware.universe

docs/contributing/coding-guidelines/ros-nodes/.pages, docs/contributing/coding-guidelines/ros-nodes/coordinate-system.md, docs/contributing/coding-guidelines/ros-nodes/naming.md, docs/contributing/coding-guidelines/ros-nodes/topic-namespaces.md, docs/design/autoware-interfaces/components/.pages, docs/how-to-guides/others/debug-autoware.md
@kenji-miyake  Hi:
This PR fix some typo and page navigation problem of my previous PR, please help me merge this PR, thanks.
=> fix: fix syntax and page index

docs/contributing/documentation-guidelines/index.md, docs/installation/autoware/docker-installation-devel.md, docs/installation/autoware/source-installation.md, docs/support/.pages, docs/support/index.md, docs/support/troubleshooting/.pages, docs/support/troubleshooting/index.md, docs/support/troubleshooting/performance-troubleshooting.md
The current troubleshooting section for improving performance in ROS is concise and accurate, but it could be improved to provide more helpful information to users.
This pull request aims to enhance the troubleshooting section by providing additional information and tips that could help users identify and resolve performance issues in ROS. …
=> docs(troubleshooting): improve performance troubleshooting section

docs/design/autoware-architecture/planning/index.md, docs/how-to-guides/integrating-autoware/creating-maps/index.md, docs/installation/autoware/source-installation.md
This will fix the failed links in Autoware Documentation.
=> fix: update invalid links in the documentation files

.github/sync-files.yaml
Fix https://github.com/autowarefoundation/autoware-documentation/pull/397/files#r1231658842.
=> ci(sync-files): fix source path

docs/installation/autoware/source-installation.md
docs: add description of where to pull repository when updating workspace
=> docs: add description of where to pull repository when updating workspace

docs/design/autoware-interfaces/components/perception-interface.md
Fix spelling in perception interface documentation.
=> fix(perception-interface): fix typos add missing links

docs/design/autoware-interfaces/components/.pages
Update autoware-interfaces/components/.pages to show "sensing.md" and "perception-interface.md"
=> feat: update autoware-interfaces pages

docs/reference-hw/cameras.md
The pull request proposes to add  TIER IV's automotive HDR camera products to the reference hardware list.
=> docs(reference-hw): add tier iv camera

docs/models/index.md
Between when https://github.com/autowarefoundation/autoware/pull/3375 was submitted and now there have been new artifacts added to `tensorrt_yolox`
See https://github.com/autowarefoundation/autoware.universe/issues/3137
=> docs: add updated artifacts for tensorrt_yolox

docs/reference-hw/cameras.md
Fix wrong TIER IV Camera web link
=> docs: fix tier iv camera link

docs/.pages
Configure GitHub Pages settings to include the models page.
=> chore: add models to github pages

.github/workflows/deploy-docs.yaml
Updates the label based on:
- https://github.com/autowarefoundation/autoware/issues/3955
=> ci(deploy-docs): update the bot label

docs/how-to-guides/others/using-divided-map.md
=> fix(docs): fix url for divided map

docs/index.md
Fix broken link to autoware website.
=> fix: fix link in the introduction page

docs/support/troubleshooting/index.md
docs: add simple guidance for locating died process with gdb tool 
=> docs: add simple guidance for locating died process with gdb tool 

docs/how-to-guides/integrating-autoware/tuning-parameters-and-performance/evaluating-controller-performance.md
controller_performance_analysis.launch.xml -> control_performance_analysis.launch.xml
=> fix: file name typo

docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/SteeringFactor.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/VelocityFactor.md, yaml/autoware-interfaces.yaml
Update planning factor types to match latest message definition.
=> feat(ad-api): update planning factor types

docs/installation/autoware/docker-installation.md
This PR adds the `-download-artifacts` option to `docker-installation.md`.
=> feat(doc): add `--download-artifacts` option to docker-installation.md

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/awsim-tutorial.md
Moving the updated table here to allow fair editing and a single source of comparison for it.
Related:
- https://github.com/autowarefoundation/AWSIM-Labs/pull/90
=> feat: add the awsim labs comparison table

docs/design/autoware-interfaces/ad-api/features/diagnostics/data.drawio.svg, docs/design/autoware-interfaces/ad-api/list/api/system/diagnostics/status.md, docs/design/autoware-interfaces/ad-api/list/api/system/diagnostics/struct.md, docs/design/autoware-interfaces/ad-api/list/api/system/heartbeat.md, docs/design/autoware-interfaces/ad-api/list/index.md, docs/design/autoware-interfaces/ad-api/release.md
Update AD API documents for v1.3.0 release. [See release note page for details.](https://autowarefoundation.github.io/autoware-documentation/pr-559/design/autoware-interfaces/ad-api/release/)
Related link: https://github.com/autowarefoundation/autoware.universe/pull/7139
=> docs(ad-api): release adapi v1.3.0

docs/installation/autoware/docker-installation.md
Reverts autowarefoundation/autoware-documentation#556
ref. https://github.com/autowarefoundation/autoware/pull/4864
=> feat(doc): revert "feat(doc): add `--download-artifacts` option to docker-installation.md"

docs/design/autoware-interfaces/ad-api/list/api/routing/set_route.md, docs/design/autoware-interfaces/ad-api/list/api/routing/set_route_points.md
Add description about the state of the route set API.
=> feat(ad-api): add routing api description

docs/design/autoware-architecture/perception/index.md
=> fix(perception-architecture): correct a typo

docs/contributing/coding-guidelines/ros-nodes/directory-structure.md
=> fix(directory-structure.md): update broken link

docs/design/autoware-interfaces/ad-api/features/routing.md, docs/design/autoware-interfaces/ad-api/list/api/routing/change_route.md, docs/design/autoware-interfaces/ad-api/list/api/routing/change_route_points.md, docs/design/autoware-interfaces/ad-api/list/index.md
Add route change API. https://github.com/orgs/autowarefoundation/discussions/4983
=> feat(ad-api): add route change api

docs/how-to-guides/others/using-divided-map.md
udpate the link of pointcloud_divider
related PR
https://github.com/autowarefoundation/autoware.universe/pull/8823
=> docs: udpate the link of pointcloud_divider

docs/installation/autoware/source-installation.md
Part of:
- https://github.com/autowarefoundation/autoware/issues/4534
⚠️🚨Should be merged after:
- https://github.com/autowarefoundation/autoware/pull/4838
=> feat(source-installation): add manual instructions for the rviz theme

docs/tutorials/ad-hoc-simulation/digital-twin-simulation/carla-tutorial.md
Update the content of zenoh_carla_bridge in CARLA simulator page.
=> docs: update zenoh_carla_bridge tutorial in Carla page

docs/how-to-guides/integrating-autoware/creating-vehicle-and-sensor-model/calibrating-sensors/calibration-tools/index.md
Update .repos file name in calibration tools guide.
This change is based on [tier4/CalibrationTools](https://github.com/tier4/CalibrationTools).
None.
None.
=> docs: update .repos file name in calibration tools guide

docs/installation/autoware/docker-installation.md
This reverts commit https://github.com/autowarefoundation/autoware-documentation/pull/648. 
Refers to https://github.com/autowarefoundation/autoware/pull/5876
None.
None.
=> docs: revert "add artifacts path to run command (#648)"

docs/design/autoware-interfaces/ad-api/list/api/vehicle/command/pedals.md, docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/srv/SendMrmRequest.md, yaml/autoware-interfaces.yaml
Fix field name.
Run mike deploy command.
None.
None.
=> fix(ad-api): fix message field name

docs/installation/autoware/docker-installation.md
Missing revert (please see https://github.com/autowarefoundation/autoware/issues/5920)
None.
None.
=> docs: revert "revert "add artifacts path to run command (#648)" (#652)"

docs/design/autoware-interfaces/ad-api/types/autoware_adapi_v1_msgs/msg/MrmRequest.md, yaml/autoware-interfaces.yaml
Update to latest message definition.
https://github.com/autowarefoundation/autoware_adapi_msgs/pull/91
None
None.
None.
=> fix(ad-api): fix mrm request message

docs/roadmap/multi-year-roadmap/index.md
This updates the Multi-year Roadmap page.
The objectives are already reviewed by the TSC, SPC, and the Board of Directors of the AWF.
None.
None.
=> docs: update-multiyear-roadmap

.github/workflows/deploy-docs.yaml
- Continuation of https://github.com/autowarefoundation/autoware-documentation/pull/691
Fix the bug where it skips deploy-docs with success.
None.
None.
=> ci(deploy-docs): fix require-label requirement

.github/workflows/deploy-docs.yaml
This PR fixes the issue where we don't have require-label requirement when pushed to main or workflow_dispatch conditions.
None.
None.
=> ci(deploy-docs): fix on: push condition
